export const GIT_REPO_LIST_REQUEST = "GIT_REPO_LIST_REQUEST";
export const GIT_REPO_LIST_SUCCESS = "GIT_REPO_LIST_SUCCESS";
export const GIT_REPO_LIST_ERROR = "GIT_REPO_LIST_ERROR";
export const GIT_REPO_LIST_UPDATE = "GIT_REPO_LIST_UPDATE";
export const GIT_REPO_LIST_UPDATE_SUCCESS = "GIT_REPO_LIST_UPDATE_SUCCESS";
